### ISSUE TITLE
Colors not working.

### ISSUE THREAD

**Issue by kadamski** [gabesoft/vim-ags#1]
After searching, my result looks like this:

```
[1;31mdrivers/mmc/core/debugfs.c[0m[K
[1;30m 200 [0m[K-
[1;30m 201 [0m[K-   mmc_claim_host(host);
[1;30m 202 [0m[K-   mmc_set_clock(host, (unsigned int) val);
[1;30m 203 [0m[K:2: [32;40mmmc_release_host[0m[K(host);
[1;30m 204 [0m[K-
[1;30m 205 [0m[K-   return 0;
[1;30m 206 [0m[K-}
```

There are no colors and escape characters are seen so obviously something went wrong. Tested on both vim and gvim 7.4 on Linux.

**Comment by egradman** [comment]
same on OSX console vim

**Comment by gabesoft** [comment]
Looks like vim is not picking up the syntax highlighting. Can you verify that the search results window has filetype=agsv? Run set ft? in the search window

**Comment by egradman** [comment]
filetype=agsv <— that’s what I see.

On Mon, Mar 16, 2015 at 2:51 PM, Gabriel Adomnicai <notifications@github.com

> wrote:
> 
> Looks like vim is not picking up the syntax highlighting. Can you verify
> that the search results window has filetype=agsv? Run set ft? in the search
> window
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gabesoft/vim-ags/issues/1#issuecomment-81957327.

## 

_Eric Gradman_
CTO & Mad Inventor
_P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
_TW:_ @egradman http://www.twitter.com/egradman

_TWO BIT CIRCUS_
Engineering Entertainment

Inventors | Developers | Performers

**Comment by gabesoft** [comment]
can you also check conceallevel and concealcursor, they should be 3 and nvic respectively in the search window

**Comment by egradman** [comment]
they are

On Mon, Mar 16, 2015 at 6:01 PM, Gabriel Adomnicai <notifications@github.com

> wrote:
> 
> can you also check conceallevel and concealcursor, they should be 3 and
> nvic respectively in the search window
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gabesoft/vim-ags/issues/1#issuecomment-82012310.

## 

_Eric Gradman_
CTO & Mad Inventor
_P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
_TW:_ @egradman http://www.twitter.com/egradman

_TWO BIT CIRCUS_
Engineering Entertainment

Inventors | Developers | Performers

**Comment by gabesoft** [comment]
One more thing to check is to make sure your vim is compiled with the conceal feature. When you run :version do you see +conceal ?

**Comment by kadamski** [comment]
In my case filetype was not set to any value, setting it manually fixed the problem. And the reason for that was that I did not restart my vim after doing "BundleInstall". It seems that my vundle failed at inserting ftdetect rules after installation.

**Comment by egradman** [comment]
Yup, it has +conceal.  I installed this plugin using pathogen, btw.

On Tue, Mar 17, 2015 at 12:48 AM, Krzysztof A. Adamski <
notifications@github.com> wrote:

> In my case filetype was not set to any value, setting it manually fixed
> the problem. And the reason for that was that I did not restart my vim
> after doing "BundleInstall". It seems that my vundle failed at inserting
> ftdetect rules after installation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gabesoft/vim-ags/issues/1#issuecomment-82188794.

## 

_Eric Gradman_
CTO & Mad Inventor
_P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
_TW:_ @egradman http://www.twitter.com/egradman

_TWO BIT CIRCUS_
Engineering Entertainment

Inventors | Developers | Performers

**Comment by gabesoft** [comment]
@egradman not sure why the syntax highlight is not picking up. Do you mind pasting a few lines from the search results window.

**Comment by egradman** [comment]
here’s a screenshot.  The colors of the brackets are due to rainbow-parens
(come to think of it, perhaps if I disable that…)

https://www.dropbox.com/s/3ay46jywg7unz6x/Screenshot%202015-03-17%2014.11.07.png?dl=0

On Tue, Mar 17, 2015 at 1:45 PM, Gabriel Adomnicai <notifications@github.com

> wrote:
> 
> @egradman https://github.com/egradman not sure why the syntax highlight
> is not picking up. Do you mind pasting a few lines from the search results
> window.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gabesoft/vim-ags/issues/1#issuecomment-82592138.

## 

_Eric Gradman_
CTO & Mad Inventor
_P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
_TW:_ @egradman http://www.twitter.com/egradman

_TWO BIT CIRCUS_
Engineering Entertainment

Inventors | Developers | Performers

**Comment by egradman** [comment]
I just restarted vim with just your plugin and it works fine, so its
definitely a conflict with something else I’m running.  I’ll figure out
which one it is and report back.

On Tue, Mar 17, 2015 at 2:11 PM, Eric Gradman eric@gradman.com wrote:

> here’s a screenshot.  The colors of the brackets are due to rainbow-parens
> (come to think of it, perhaps if I disable that…)
> 
> https://www.dropbox.com/s/3ay46jywg7unz6x/Screenshot%202015-03-17%2014.11.07.png?dl=0
> 
> On Tue, Mar 17, 2015 at 1:45 PM, Gabriel Adomnicai <
> notifications@github.com> wrote:
> 
> > @egradman https://github.com/egradman not sure why the syntax
> > highlight is not picking up. Do you mind pasting a few lines from the
> > search results window.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gabesoft/vim-ags/issues/1#issuecomment-82592138.
> 
> ## 
> 
> _Eric Gradman_
> CTO & Mad Inventor
> _P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
> _TW:_ @egradman http://www.twitter.com/egradman
> 
> _TWO BIT CIRCUS_
> Engineering Entertainment
> 
> Inventors | Developers | Performers

## 

_Eric Gradman_
CTO & Mad Inventor
_P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
_TW:_ @egradman http://www.twitter.com/egradman

_TWO BIT CIRCUS_
Engineering Entertainment

Inventors | Developers | Performers

**Comment by egradman** [comment]
Okay, it's definitely a conflict with https://github.com/luochen1990/rainbow

**Comment by gabesoft** [comment]
@egradman cool, that's good to know. I'll look at the rainbow plugin when I get home and see if there's anything I can do in vim-ags to eliminate the conflict.

**Comment by gabesoft** [comment]
Actually, I think it's just a matter of configuring the g:rainbow_conf option to disable rainbow parens for filetypes of agsv. Something like `let g:rainbow_conf = { 'separately' : { 'agsv' : 0 } }` should do the trick

**Comment by egradman** [comment]
so it would appear.  this doesn’t seem to work however but I don’t think
it’s the fault of your plugin.

On Tue, Mar 17, 2015 at 3:50 PM, Gabriel Adomnicai <notifications@github.com

> wrote:
> 
> Actually, I think it's just a matter of configuring the g:rainbow_conf
> option to disable rainbow parens for filetypes of agsv. Something like let
> g:rainbow_conf = { 'separately' : { 'agsv' : 0 } } should do the trick
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gabesoft/vim-ags/issues/1#issuecomment-82631521.

## 

_Eric Gradman_
CTO & Mad Inventor
_P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
_TW:_ @egradman http://www.twitter.com/egradman

_TWO BIT CIRCUS_
Engineering Entertainment

Inventors | Developers | Performers

**Comment by gabesoft** [comment]
I've tried the rainbow plugin and it seems to work properly. After I added this to my vimrc

```
let g:rainbow_conf = {
      \ 'separately' : { 'agsv' : 0 }
      \ }
let g:rainbow_active = 1
```

the search results picked up the correct syntax. You may need to restart vim for the changes to take effect.

**Comment by egradman** [comment]
I may have spoken too soon.  I’m currently running vim with ONLY your
plugin and I’m seeing the same results...

What threw me off is that it seems to be dependent on my cwd when I run the
command.

Two fresh sessions of vim in two different directories (in two adjacent
iTerm windows): one renders correctly, one renders incorrectly.

On Wed, Mar 18, 2015 at 11:13 AM, Gabriel Adomnicai <
notifications@github.com> wrote:

> I've tried the rainbow plugin and it seems to work properly. After I added
> this to my vimrc
> 
> let g:rainbow_conf = {
>       \ 'separately' : { 'agsv' : 0 }
>       \ }
> let g:rainbow_active = 1
> 
> the search results picked up the correct syntax. You may need to restart
> vim for the changes to take effect.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gabesoft/vim-ags/issues/1#issuecomment-83106116.

## 

_Eric Gradman_
CTO & Mad Inventor
_P:_ 213-268-6253 | _W:_ twobitcircus.com http://www.twobitcircus.com/
_TW:_ @egradman http://www.twitter.com/egradman

_TWO BIT CIRCUS_
Engineering Entertainment

Inventors | Developers | Performers

**Comment by gabesoft** [comment]
What do the results look for the one that renders incorrectly?

**Comment by megalithic** [comment]
:+1: that mostly fixed it for me, thanks Gabriel.

**Comment by gabesoft** [comment]
I'll close this as it seems to be a configuration issue.
