### ISSUE TITLE
Lightline integration on readme

### ISSUE THREAD

**Issue by smarquez1** [gabesoft/vim-ags#14]
Great plugin! Can you add more information on the readme file on how to integrate it with lightline?

**Comment by gabesoft** [comment]
Added docs (316612572c59f1d5a8b0efebc408584230e8921d). But I didn't add anything specific to a particular status line plugin. For an example on how to integrate it with lightline see this https://github.com/gabesoft/dotfiles/blob/master/.vim/bundle.vim#L339

**Comment by smarquez1** [comment]
Thanks a lot. Keep up the good work!
