### ISSUE TITLE
reuse last window behavior

### ISSUE THREAD

**Issue by darrinholst** [gabesoft/vim-ags#19]
I have a nerdtree window open a lot of the times like...

![2015-10-23 at 7 18 am](https://cloud.githubusercontent.com/assets/4854/10692339/7de9a870-7956-11e5-8d60-988aa601cc80.png)

My cursor is in the file contents window (right most) and when I do a search and press enter in the search results it always opens in the nerdtree window like...

![2015-10-23 at 7 21 am](https://cloud.githubusercontent.com/assets/4854/10692368/b36db2a2-7956-11e5-84c1-8c43a48fb730.png)

Is this expected behavior? Some other issue I was reading gave me the impression that it would use the last window you were using.

**Comment by gabesoft** [comment]
When you press enter that's the case. But there are other ways to open a window from the search results. Press u in the search results to see all options.

**Comment by darrinholst** [comment]
Ok, I see what it's doing now with `winnr('#')` and `ou` is what I want, but I want to use the window I initiated the search from, not the window that `CTRL-W_p` will take you to. I hope that makes sense.
1. open vim
2. `:vs`
3. `:Ags foo`
4. `<enter>`
5. I would expect that to open in the left side, but it opens in the right.

Any idea if it's possible to get it to open up in the window you came from?

![vim-ags](https://cloud.githubusercontent.com/assets/4854/10703297/a671415c-7994-11e5-9513-f3026e9f0a0c.gif)

**Comment by gabesoft** [comment]
I fixed it so it opens in the window that originated the search. But, this may affect people who open their nerd tree on the right and originate searches from there. I'll make this behavior optional if I get issues about that.

**Comment by darrinholst** [comment]
Thanks for the fix
