### ISSUE TITLE
Use system PATH by default to look for ag executable

### ISSUE THREAD

**Issue by kwbr** [gabesoft/vim-ags#2]
Most people install ag into a directory which is part of their PATH variable. To have a simpler installation without configuring anything, vim-ags should look for the executable in the PATH first and not under a hard coded path.

See for example, like rking/ag plugin does it.

**Comment by gabesoft** [comment]
Fixed by 2645f706387458f49b21f2c0af6bd5f45dcd8f72

**Comment by kwbr** [comment]
Thanks!
