### ISSUE TITLE
Regression for searches with spaces?

### ISSUE THREAD

**Issue by af** [gabesoft/vim-ags#22]
Hi,

I just updated from `3b95ee7` to latest master for the neovim async support (very nice by the way!) One thing I noticed is that something in between seems to have broken searches with spaces in them.

For example, `:Ags "my string"` would return results before, now I get no results even though running `ag "my string"` in the CLI gives the same results as before. Searches that don't have spaces still seem to work fine.

I'm using a recent-ish neovim if that helps.

**Comment by gabesoft** [comment]
Yea I'm able to reproduce it also. It doesn't happen in vim, just in neovim. I'll take a closer look at this soon.

**Comment by af** [comment]
Works great now, thanks!
