### ISSUE TITLE
Edit mode

### ISSUE THREAD

**Issue by wikimatze** [gabesoft/vim-ags#25]
When pressing `E` I can edit all the files without going through the process of opening every single file, make the change and close it. How can I save all the files when I'm in `E` mode?

When I quit the window, I get:

``` sh
E37: No write since last change
E162: No write since last change for buffer "search-results.agse"
```

Cheers,
Matthias

**Comment by gabesoft** [comment]
Just save like you would any normal buffer.

**Comment by gabesoft** [comment]
:w

**Comment by wikimatze** [comment]
Jup, that was the easy the solution to this problem.
