### ISSUE TITLE
[Question] Mapping :Ags

### ISSUE THREAD

**Issue by patelsan** [gabesoft/vim-ags#26]
Please excuse me for asking a basic question - I am relatively new to VIM.

How can I map ":Ags" to something easy to type command? Maybe just "//", so a search could be performed using "//SearchText"

**Comment by gabesoft** [comment]
You can do it by using `nnoremap` or a similar command (do an `:h nnoremap` in vim to learn more). For example I have the following two lines in my .vimrc

```
nnoremap <Leader>a :Ags<Space>
nnoremap <Leader><Leader>a :AgsQuit<CR>
```

That maps `:Ags` to `,a` and `:AgsQuit` to `,,a` (my leader key is ,)
