### ISSUE TITLE
Can't cancel long searches

### ISSUE THREAD

**Issue by mk12** [gabesoft/vim-ags#27]
I'm using Neovim. When I accidentally search from my home directory, or from anywhere that would take way too long, Ags freezes the whole UI so I have to kill the terminal to get out of vim. It does display some messages and the cursor jumps around in the search results window, but when I try pressing q or Ctrl-C nothing happens.

**Comment by gabesoft** [comment]
Yea, there's no explicit functionality in place to kill long searches. That sounds like a good feature to have though. It would probably only work when the async flag is enabled. I'll take a look when I get a chance. Or, I'd accept a pull request for it as well.
