### ISSUE TITLE
Feature request: Open a result and dismiss search-results.agsv in one step

### ISSUE THREAD

**Issue by af** [gabesoft/vim-ags#5]
Sometimes you're only looking for a single search result, and then you have no further need for the results window. Ideally in this case you could open the result and dismiss the results window with a single keybinding (essentially, `UO` and `q` combined into one step). Thoughts on adding this as a built-in action?

**Comment by gabesoft** [comment]
`os` pretty much does this, except it does not delete the search buffer

**Comment by af** [comment]
It's similar, but (at least in my test) it opens the result in the same window as the search. The desired behaviour would open it in the original window (like `<CR>` works now).

**Comment by gabesoft** [comment]
Oh, I see, yea that makes sense. I'll try to add this sometimes soon.
