### ISSUE TITLE
Adding a bulk replace à la "En Masse"?

### ISSUE THREAD

**Issue by renajohn** [gabesoft/vim-ags#7]
This plug-in is awesome. For me, the one thing that could make this plugin a must have is a feature a la "En Masse", aka replace:
https://github.com/Wolfy87/vim-enmasse

The workflow I have in mind is:
1. Do a search with Ags
2. Edit the Ags buffer with `%s//`
3. Run `:w` in Ags buffer to magically edit all files

**Comment by gabesoft** [comment]
Yea that sounds like a pretty useful feature. It would avoid having to open each buffer manually for search and replaces. I'll give it some thought.

**Comment by mohitleo9** [comment]
Just a quick thought on this, I use very similar workflow.
I first use some search tool (Ack or Ggrep) that populates the location list and then I use this plugin https://github.com/Peeja/vim-cdo to run replace command on those like
Cdo s/something/somethingelse.
So it would be really cool if there was some way of populating the location buffer or quickfix buffer with the results of ags.

**Comment by gabesoft** [comment]
@mohitleo9, @renajohn actually, I'm working on an editable version of the search results. It's still a work in progress but I could use some feedback. It's on the feature-edit branch. In the search results window pressing E will make the results editable, after which lines can be edited and on write all files changed are updated. No lines can be added or removed though.

**Comment by renajohn** [comment]
Cool! I'll have a look during the day (Geneva time). Any reason you want to have an edit **mode** with `E` as opposed to using the buffer save as the trigger? It looks like an extra step to me.

Another side comment, I got tricked yesterday with EnMasse. I've bulk edited several files but some of them had changed between the moment I did my Ag and the moment I've saved my modifications with EnMasse. The result was so bad I had to revert some of my files. Do you think it would be possible to refuse the edition if the any file has changed between the moment the search was done and the moment the edit is saved?

**Comment by renajohn** [comment]
Had a look at your branch. It's awesome, well done!

### Comments:
- How can I go out of edit mode?
- It feels disturbing to be able to edit line numbers. I would remove them in edit mode
- It would be nice to be able to add lines/remove lines, but I can leave without it

### Bugs
- Deleting file number will delete as many characters in the file than deleted numbers. For instance, if I have:

```
123 if (foo) {
```

and I delete `12` then save, the `if` in my target file will be deleted. I will only have:

```
(foo) {
```

**Comment by gabesoft** [comment]
Thanks for the quick feedback. Here are some answers to your comments
- Once in edit mode the only way to exit is either to re-run the search (it will open in the same window) or to close the results buffer if done (I've added an AgsQuit command for that as well). 
- The line numbers, as well as the file paths are not meant to be edited, they are there just as visual cues. The width of the line numbers is used to detect where the actual file line starts. So, deleting any characters from there will result in deleting characters from the actual file line. Come to think of it, this could interfere with the search and replace if replacing numbers and they happen to match any values in the line number. I think I'll add a setting to hide/show those and maybe I'll hide them by default. 
- Adding/deleting lines make things more complicated and I'm not sure there's a good use case for it. I may reconsider this if there's enough demand for it.
- Regarding aborting the edits if a file has changed, I think I can put something in place. Maybe, I'll have a setting to enable/disable this behavior. I will only be able to detect if any of the lines that appear in the search results has changed. By the way you can undo any edits just by undoing them in the search window and then re-saving.

**Comment by renajohn** [comment]
> Once in edit mode the only way to exit is either to re-run the search (it will open in the same window) or to close the results buffer if done (I've added an AgsQuit command for that as well).

Do you think you could map `q` to re-run the search when in edit mode? The idea would be to hit `E` and modify a few occurrences of the search term then hit `q` to quite edit mode and have an updated version of the search.

> The line numbers, as well as the file paths are not meant to be edited, they are there just as visual cues. The width of the line numbers is used to detect where the actual file line starts. So, deleting any characters from there will result in deleting characters from the actual file line. Come to think of it, this could interfere with the search and replace if replacing numbers and they happen to match any values in the line number. I think I'll add a setting to hide/show those and maybe I'll hide them by default.
> Adding/deleting lines make things more complicated and I'm not sure there's a good use case for it. I may reconsider this if there's enough demand for it.

Having a setting and hiding line number by default, is most likely the best solution. I would not even bother to have a setting to activate line number in edit mode, but it's just my opinion.

> Regarding aborting the edits if a file has changed, I think I can put something in place. Maybe, I'll have a setting to enable/disable this behavior. I will only be able to detect if any of the lines that appear in the search results has changed. By the way you can undo any edits just by undoing them in the search window and then re-saving.

Sounds good. Thank you for all your work! I'm already using your branch daily. It's super useful.

**Comment by renajohn** [comment]
Just seen that line number option is already in. Wow!

**Comment by gabesoft** [comment]
> Do you think you could map `q` to re-run the search when in edit mode? The idea would be to hit `E` and modify a few occurrences of the search term then hit `q` to quite edit mode and have an updated version of the search.

I don't really want to add any maps in edit mode. Some people may want the original `q` functionality. But you could add some maps if you wish.
For example I have these two maps in my vimrc

```
nnoremap <LEADER>a :Ags<SPACE>
nnoremap <LEADER><LEADER>a :AgsQuit<CR>
```

And so I can easily re-run the search or quit the search window.

**Comment by renajohn** [comment]
Ok, makes sense. I do love macro so I can understand you would use them for a bulk replace.

I'll follow your advice and add mappings in my nvimrc (I'm using NeoVim since this week. It rocks!). I already have that one in my nvimrc:

```
nnoremap <LEADER>a :Ags<SPACE>
```

I'll add the other one, it looks really handy.

**Comment by renajohn** [comment]
You can close this issue if you want. Thank you so much for this new feature!

**Comment by gabesoft** [comment]
You're welcome, and thanks for helping out with this feature. I'll close this once I merge the feature branch into master.

**Comment by gabesoft** [comment]
Fixed
